ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'USER';

ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'USER';

UPDATE "users"
SET "role" = 'USER'
WHERE "role"::text IN ('INVESTIGATOR', 'ANALYST', 'AUDITOR');
